/**
 * 系統・方向ごとの行先・経由地マスタ
 * キー：系統番号_方向キー
 */
const routeMaster = {
    "35_北": {
        via: "地下鉄今里・鴫野駅前・地下鉄蒲生四丁目方面",
        viaEng: "Via Subway Imazato",
        dest: "守口車庫前",
        destEng: "For Moriguchishako-mae",
        destKana: "もりぐちしゃこまえ",
        msg1: "★地下鉄今里乗換★今里筋線・千日前線",
        msg2: "★鴫野駅前乗換★JR学研都市線・おおさか東線",
    },
    "35_南": {
        via: "",
        viaEng: "",
        dest: "杭全",
        destEng: "For Kumata",
        destKana: "くまた",
        msg1: "★杭全乗換★JR大和路線",
        msg2: "",
    },
    "35A_北": {
        via: "大池橋・中川二丁目・中川西公園前方面",
        viaEng: "Via Oikebashi",
        dest: "地下鉄今里",
        destEng: "For Subway Imazato",
        destKana: "ちかてついまざと",
        msg1: "★地下鉄今里乗換★今里筋線・千日前線",
        msg2: "",
    },
    "35A_南": {
        via: "",
        viaEng: "",
        dest: "杭全",
        destEng: "For Kumata",
        destKana: "くまた",
        msg1: "★杭全乗換★JR大和路線",
        msg2: "",
    },
    "85_北": {
        via: "地下鉄今里・玉造・心斎橋方面",
        viaEng: "Via Subway Imazato",
        dest: "なんば",
        destEng: "For Namba",
        destKana: "",
        msg1: "★地下鉄今里乗換★今里筋線・千日前線",
        msg2: "★玉造乗換★JR大阪環状線",
    },
    "85_南": {
        via: "",
        viaEng: "",
        dest: "杭全",
        destEng: "For Kumata",
        destKana: "くまた",
        msg1: "★杭全乗換★JR大和路線",
        msg2: "",
    },
    "73_北": {
        via: "生野区役所・鶴橋駅前・日本橋一丁目方面",
        viaEng: "Via Tsuruhashi Station",
        dest: "なんば",
        destEng: "For Namba",
        destKana: "",
        msg1: "★鶴橋駅前乗換★千日前線、JR大阪環状線、近鉄線",
        msg2: "",
    },
    "73_南": {
        via: "杭全・今川二丁目・地下鉄平野方面",
        viaEng: "Via Kumata",
        dest: "出戸バスターミナル",
        destEng: "For Deto Bus Terminal",
        destKana: "でとばすたーみなる",
        msg1: "★杭全乗換★JR大和路線",
        msg2: "★地下鉄平野乗換★谷町線",
    },
    "13_北": {
        via: "大池橋方面",
        viaEng: "Via Oikebashi",
        dest: "北巽バスターミナル",
        destKana: "きたたつみばすたーみなる",
        destEng: "For Kita-Tatsumi Bus Terminal",
        msg1: "★北巽バスターミナル乗換★千日前線",
        msg2: "",
    },
    "13_南": {
        via: "舎利寺・百済・寺田町駅前方面",
        viaEng: "Via Kudara",
        dest: "あべの橋",
        destEng: "For Abenobashi",
        destKana: "あべのばし",
        msg1: "★寺田町駅前乗換★JR大阪環状線",
        msg2: "★あべの橋乗換★御堂筋線・谷町線、JR線、近鉄線、阪堺線",
    },

    "00_試": {
        via: "大阪シティバス",
        viaEng: "Osaka City Bus",
        dest: "試験中",
        destEng: "Test",
        destKana: "しけんちゅう",
        msg1: "",
        msg2: "",
    },
};
